#!/bin/bash
echo "Connecting to database..."
echo "Refreshing tables..."
mysql --user=mbax4hw2 --host=dbhost.cs.man.ac.uk --password=BestTeam2014 2014_comp10120_x2 < initsql.sql

echo "Reinit'd tables"
