#!/bin/bash
read -p "Group DB? (y/n)" grp;
read -p "Username: " user;

if [ "$grp" = "n" ]; then
    db=$user
else
    db="2014_comp10120_x2"
fi

stty -echo
read -p "Password: " passw; 
stty echo

echo "Connecting to database..."
echo "Refreshing tables..."
echo $db
mysql --user=$user --host=dbhost.cs.man.ac.uk --password=$passw $db < initsql.sql

echo "Reinit'd tables"
